### ISSUE TITLE
slowmotion servo setSpeed questions

### ISSUE THREAD

**Issue by antoniosap** [Locoduino/SlowMotionServo#2]
i try many combinations of parameters pan/speed, and full/half/fractions of full travel
if speed=1 the traveling time of full stroke is 10s. (only first time)
and if have pan of 0.1 the axis do not brake as start acceleration. 
is not so smooth on brake. not symmetrical accelerations.

how to manage servo heavy inertia ?

```
PAN:0.00000:SPEED:  1.000
PAN:1.00000:SPEED:100.000
PAN:0.00000:SPEED:500.000
PAN:0.50000:SPEED:500.000
PAN:0.60000:SPEED:  0.050
PAN:0.70000:SPEED: 15.000
PAN:0.80000:SPEED:1500.000
PAN:0.85000:SPEED:  0.001
PAN:0.80000:SPEED:15000.000
PAN:0.50000:SPEED:60000.000
PAN:0.20000:SPEED:  0.000
PAN:0.30000:SPEED:  0.500
PAN:0.00000:SPEED: 20.000
PAN:1.00000:SPEED:20000.000
PAN:0.00000:SPEED:  2.000
PAN:1.00000:SPEED:  0.100
PAN:0.00000:SPEED:  1.000
PAN:1.00000:SPEED:  1.000
PAN:1.00000:SPEED:10000.000
PAN:0.20000:SPEED: 15.000

```

**Comment by Koryphon** [comment]
First of all, the smoothness of the movement depends on the quality of the servo, both mechanical and electronic. For example, if you use an SG90, you are unlikely to have a smooth movement.

But I didn't quite understand what you're trying to do. Attach your sketch to your answer so I can see for myself.

**Comment by antoniosap** [comment]
servo is hitec 
main source code follow
you can search for word 'servo', libraries not attached
[wemos_pan_box_2.ino.zip](https://github.com/Locoduino/SlowMotionServo/files/2729610/wemos_pan_box_2.ino.zip)

**Comment by Koryphon** [comment]
Some comments on speed. 

With speed = 100, the time to travel will be 0,1s. With 60000, it will 166µs and probably this time has elapsed between 2 calls to update. In any case the servo is unable to follow the trajectory. To have smoothness, you must have a slowly evolving trajectory. Why use SlowMotionServo to go immediately from 0.0 to 1.0 ?

**Comment by antoniosap** [comment]
I need quick pan with the camera mount and limit the inertia. accelerations and slow braking

**Comment by Koryphon** [comment]
Ok but how much quick ? Maybe it is the SMSSmooth trajectory which has a too fast acceleration and brake. FYI it is the following trajectory:

![SMSSmooth trajectory](
http://www.locoduino.org/local/cache-vignettes/L400xH351/smssmooth-c6a7a.png?1519895021)

**Comment by antoniosap** [comment]
this is (1.0 - cos(time * PI))/2.0
have you more smooth curve ?

**Comment by Koryphon** [comment]
No but you can provide your own curve by inheriting from SlowMotionServo class. For instance SMSSmooth is like that:

```C++
class SMSSmooth : public SlowMotionServo
{
public:
  float slope(float time) { return (1.0 - cos(time * PI))/2.0; }
  virtual float slopeUp(float time) {  return slope(time); }
  virtual float slopeDown(float time) {  return slope(time); };
};
```

**Comment by antoniosap** [comment]
this is the final sigmoid-s curve adopted also for sub interval of [0..1]

```
class MySMSSmooth : public SMSSmooth {
private:
  // sigmoid-s: 1 / (1 + exp(-x * 5 + 5)) x in [0..2], 
  // source time domain in [0, 1]
  float min_x = 0;
  float max_x = 1;
  
public:
  void setDomain(float min_d, float max_d) {
    if (min_d <= max_d) {
      min_x = min_d;
      max_x = max_d;
    } else {
      min_x = max_d;
      max_x = min_d;
    }
  }
  
  float mapfloat(float x, float in_min, float in_max, float out_min, float out_max) {
    return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
  }
  
  float slope(float time) {
    float t = mapfloat(time, min_x, max_x, 0.0, 2.0);
    float s = 1 / (1 + exp(-t * 5 + 5));
    float y = mapfloat(s, 0.0, 1.0, min_x, max_x);
    return y; 
  }
  virtual float slopeUp(float time) {  return slope(time); }
  virtual float slopeDown(float time) {  return slope(time); }
};
```

**Comment by Koryphon** [comment]
Nice work !

Would you mind if I add this trajectory to the library ?

**Comment by antoniosap** [comment]
yes. thanks.
